// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Qkart_WebAPI.Data;

#nullable disable

namespace QkartWebAPI.Migrations
{
    [DbContext(typeof(QkartDbContext))]
    [Migration("20230130081412_localuserupdate")]
    partial class localuserupdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Qkart_WebAPI.Models.LinkProductSeller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<int>("SellerPrice")
                        .HasColumnType("int");

                    b.Property<string>("SpecialDetails")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SellerId");

                    b.ToTable("LinkProductSellers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = new Guid("70c9af8e-da97-4c51-68d1-08dafeca85a2"),
                            SellerId = 1,
                            SellerPrice = 0
                        },
                        new
                        {
                            Id = 2,
                            ProductId = new Guid("70c9af8e-da97-4c51-68d1-08dafeca85a2"),
                            SellerId = 2,
                            SellerPrice = 0
                        },
                        new
                        {
                            Id = 3,
                            ProductId = new Guid("b44859e1-c104-4450-bf9b-2008a6858187"),
                            SellerId = 1,
                            SellerPrice = 0
                        });
                });

            modelBuilder.Entity("Qkart_WebAPI.Models.LocalUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LocalUsers");
                });

            modelBuilder.Entity("Qkart_WebAPI.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Catagory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("147e9c08-d57b-43f2-88ce-937507201720"),
                            Catagory = "Mobile",
                            Cost = 12500,
                            CreatedDate = new DateTime(2023, 1, 30, 13, 44, 12, 107, DateTimeKind.Local).AddTicks(8897),
                            Name = "Asus ZenPhone M2 Mobile Phone",
                            Rating = 4.0,
                            UpdatedDate = new DateTime(2023, 1, 30, 13, 44, 12, 107, DateTimeKind.Local).AddTicks(8907)
                        },
                        new
                        {
                            Id = new Guid("e8932946-a19e-4543-955d-2b04919c3641"),
                            Catagory = "Mobile",
                            Cost = 8500,
                            CreatedDate = new DateTime(2023, 1, 30, 13, 44, 12, 107, DateTimeKind.Local).AddTicks(8909),
                            Name = "MI Some Mobile",
                            Rating = 4.0999999999999996,
                            UpdatedDate = new DateTime(2023, 1, 30, 13, 44, 12, 107, DateTimeKind.Local).AddTicks(8910)
                        });
                });

            modelBuilder.Entity("Qkart_WebAPI.Models.Seller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SellerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SpecialDetails")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sellers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Coimbatore",
                            CreatedDate = new DateTime(2023, 1, 30, 8, 14, 12, 107, DateTimeKind.Utc).AddTicks(9000),
                            FullAddress = "Coimbatore",
                            SellerName = "InsakHomes",
                            SpecialDetails = ""
                        },
                        new
                        {
                            Id = 2,
                            City = "Coimbatore",
                            CreatedDate = new DateTime(2023, 1, 30, 8, 14, 12, 107, DateTimeKind.Utc).AddTicks(9003),
                            FullAddress = "Coimbatore",
                            SellerName = "DreamCorp",
                            SpecialDetails = ""
                        });
                });

            modelBuilder.Entity("Qkart_WebAPI.Models.LinkProductSeller", b =>
                {
                    b.HasOne("Qkart_WebAPI.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Qkart_WebAPI.Models.Seller", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Seller");
                });
#pragma warning restore 612, 618
        }
    }
}
