// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Qkart_WebAPI.Data;

#nullable disable

namespace QkartWebAPI.Migrations
{
    [DbContext(typeof(QkartDbContext))]
    [Migration("20230124114438_addproductsData")]
    partial class addproductsData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Qkart_WebAPI.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Catagory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c4539963-561a-49ec-821a-005dbe4da45d"),
                            Catagory = "Mobile",
                            Cost = 12500,
                            CreatedDate = new DateTime(2023, 1, 24, 17, 14, 38, 665, DateTimeKind.Local).AddTicks(3217),
                            Name = "Asus ZenPhone M2 Mobile Phone",
                            Rating = 4.0,
                            UpdatedDate = new DateTime(2023, 1, 24, 17, 14, 38, 665, DateTimeKind.Local).AddTicks(3229)
                        },
                        new
                        {
                            Id = new Guid("f98f5001-ffa0-4fda-a37f-5c0d0ce36bce"),
                            Catagory = "Mobile",
                            Cost = 8500,
                            CreatedDate = new DateTime(2023, 1, 24, 17, 14, 38, 665, DateTimeKind.Local).AddTicks(3232),
                            Name = "MI Some Mobile",
                            Rating = 4.0999999999999996,
                            UpdatedDate = new DateTime(2023, 1, 24, 17, 14, 38, 665, DateTimeKind.Local).AddTicks(3232)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
